services:
  mailserver:
    build: ./
    image: mailserver_custom
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    container_name: mail
    hostname: mail
    domainname: korog.lu
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /mnt/mail-storage/mail-data/:/var/mail/
      - /mnt/mail-storage/mail-state/:/var/mail-state/
      - /mnt/mail-storage/mail-logs/:/var/log/mail/
      - /mnt/mail-storage/config/:/tmp/docker-mailserver/
      - /mnt/mail-storage/config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - /mnt/mail-storage/cron/fts_xapian:/etc/cron.d/fts_xapian
      - /root/ssl/:/tmp/dms/custom-certs/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_PTRACE
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  default:
    driver: bridge
    name: dms_network
    enable_ipv6: true
